### PR TITLE
Check whether yamerl is running before assuming yaml is malformed

### LINKED ISSUE #25: Misleading error when yamerl is not running
When yamerl is not running, calling a function such as `YamlElixir.read_all_from_file("foo.yaml")` incorrectly returns `{:error, "malformed yaml"}` because the changes in #24 assume all exceptions raised are due to malformed yaml.

These functions should instead check whether yamerl is running, and provide a more useful error if it isn't.

### PR DESCRIPTION
**Pull request by samb1729**
Fixes #25

### CODE REVIEW

**Comment by KamilLelonek** [comment]
I'm not sure if I agree with that. Cannot we just enforce starting it?

**Comment by samb1729** [comment]
In my (short) experience, using the `@on_load` module attribute with `Application.ensure_all_started` seems to make distillery releases hang on launch so I want to avoid that happening for consumers of this library.

fwiw, the case I ran into this issue was when doing `iex -S mix run --no-start`, since that command prevents my project's dependencies from being loaded.

Maybe this requires a bit more thought instead of a hasty PR. I'll leave this here for now and just rely on the fact I'm aware of this issue. Thoughts very much welcome!

**Comment by KamilLelonek** [comment]
Are you sure that https://github.com/KamilLelonek/yaml-elixir/pull/23 didn't break that?

**Comment by samb1729** [comment]
#23 only shifted the requirement from `Application.ensure_all_started(:yaml_elixir)` to `Application.ensure_all_started(:yamerl)`

**Comment by KamilLelonek** [comment]
Fixed in [`2.0.2`](https://hex.pm/packages/yaml_elixir/2.0.2).

**Pull request closed without merging**
