### PR TITLE
use ~c"" for charlists

### PR DESCRIPTION
**Pull request by simonmcconnell**

### CODE REVIEW

**Review by KamilLelonek — APPROVED** [review]

**Comment by Hermanverschooten** [comment]
Can you please release a new version containing this fix, thx.

**Comment by KamilLelonek** [comment]
Done!

**Comment by Hermanverschooten** [comment]
Thanks! Although it seems 1 was overlooked, I still get a warning on compilation:
```elixir
===> Compiling yamerl
==> yaml_elixir
Compiling 6 files (.ex)
    warning: single-quoted strings represent charlists. Use ~c"" if you indeed want a charlist or use "" instead
    │
 30 │     node = unfinished_node(node, priv: {key, '$expecting_value', keyword_list})
    │                                              ~
    │
    └─ lib/yaml_elixir/yaml_node_keyword_list.ex:30:46

Generated yaml_elixir app
```

**Comment by KamilLelonek** [comment]
Oh, please provide another PR then.

**Pull request merged**
